<?php

namespace App\Http\Controllers;

use App\Enums\StepStatus;
use App\Models\HrProject;
use App\Services\StepTransitionService;
use Illuminate\Http\Request;
use Inertia\Inertia;

class HrPolicyOsController extends Controller
{
    public function __construct(
        protected StepTransitionService $stepTransitionService
    ) {
    }

    /**
     * Show HR Policy OS step (Step 5).
     */
    public function index(Request $request, HrProject $hrProject)
    {
        $user = $request->user();
        
        // Only allow HR Manager
        if (!$user->hasRole('hr_manager')) {
            abort(403);
        }

        // Check if step is unlocked
        if (!$hrProject->isStepUnlocked('hr_policy_os')) {
            return redirect()->route('hr-manager.dashboard')
                ->withErrors(['error' => 'HR Policy OS step is not yet unlocked. Please complete Step 4 first.']);
        }

        // Load all necessary data from previous steps
        $hrProject->load([
            'diagnosis',
            'company',
            'ceoPhilosophy',
            'organizationDesign',
            'performanceSystem',
            'compensationSystem',
        ]);

        // Load finalized job definitions
        $jobDefinitions = \App\Models\JobDefinition::where('hr_project_id', $hrProject->id)
            ->where('is_finalized', true)
            ->with('jobKeyword')
            ->get();

        $stepStatuses = $hrProject->step_statuses ?? [];
        $mainStepStatuses = [
            'diagnosis' => $stepStatuses['diagnosis'] ?? 'not_started',
            'job_analysis' => $stepStatuses['job_analysis'] ?? 'not_started',
            'performance' => $stepStatuses['performance'] ?? 'not_started',
            'compensation' => $stepStatuses['compensation'] ?? 'not_started',
            'hr_policy_os' => $stepStatuses['hr_policy_os'] ?? 'not_started',
        ];

        // Load existing HR Policy OS data if any
        $hrPolicyOs = \App\Models\HrPolicyOs::where('hr_project_id', $hrProject->id)->first();

        // Load admin recommendations/comments for Step 5
        $adminRecommendations = \App\Models\AdminComment::where('hr_project_id', $hrProject->id)
            ->where('step', 'hr_policy_os')
            ->where('is_recommendation', true)
            ->first();
        
        $adminComments = \App\Models\AdminComment::where('hr_project_id', $hrProject->id)
            ->where('step', 'hr_policy_os')
            ->where('is_recommendation', false)
            ->with('user')
            ->get();

        // Auto-generate policy manual from Steps 1-4 if not exists
        if (!$hrPolicyOs) {
            $autoGenerated = $this->generatePolicyManual($hrProject, $jobDefinitions);
            
            // Create initial HR Policy OS with auto-generated content
            $hrPolicyOs = \App\Models\HrPolicyOs::create([
                'hr_project_id' => $hrProject->id,
                'status' => StepStatus::IN_PROGRESS->value,
                'policy_manual' => $autoGenerated['policy_manual'],
                'system_handbook' => $autoGenerated['system_handbook'],
                'implementation_roadmap' => $autoGenerated['implementation_roadmap'],
                'analytics_blueprint' => $autoGenerated['analytics_blueprint'],
            ]);
        } else {
            // If exists but missing auto-generated content, regenerate
            $autoGenerated = $this->generatePolicyManual($hrProject, $jobDefinitions);
            $updateData = [];
            
            if (empty($hrPolicyOs->policy_manual)) {
                $updateData['policy_manual'] = $autoGenerated['policy_manual'];
            }
            if (empty($hrPolicyOs->system_handbook)) {
                $updateData['system_handbook'] = $autoGenerated['system_handbook'];
            }
            if (empty($hrPolicyOs->implementation_roadmap)) {
                $updateData['implementation_roadmap'] = $autoGenerated['implementation_roadmap'];
            }
            if (empty($hrPolicyOs->analytics_blueprint)) {
                $updateData['analytics_blueprint'] = $autoGenerated['analytics_blueprint'];
            }
            
            if (!empty($updateData)) {
                $hrPolicyOs->update($updateData);
                $hrPolicyOs->refresh();
            }
        }

        return Inertia::render('HrPolicyOs/Index', [
            'project' => $hrProject,
            'stepStatuses' => $mainStepStatuses,
            'projectId' => $hrProject->id,
            'jobDefinitions' => $jobDefinitions,
            'hrPolicyOs' => $hrPolicyOs,
            'adminRecommendations' => $adminRecommendations,
            'adminComments' => $adminComments,
        ]);
    }

    /**
     * Store HR Policy OS data.
     */
    public function store(Request $request, HrProject $hrProject)
    {
        if (!$request->user()->hasRole('hr_manager')) {
            abort(403);
        }

        $validated = $request->validate([
            'policy_manual' => ['nullable', 'array'],
            'system_handbook' => ['nullable', 'array'],
            'implementation_roadmap' => ['nullable', 'array'],
            'analytics_blueprint' => ['nullable', 'array'],
            'customizations' => ['nullable', 'array'],
        ]);

        // Store or update HR Policy OS data
        $hrPolicyOs = \App\Models\HrPolicyOs::updateOrCreate(
            ['hr_project_id' => $hrProject->id],
            array_merge($validated, [
                'status' => StepStatus::IN_PROGRESS->value,
            ])
        );

        // Update project step status
        $hrProject->setStepStatus('hr_policy_os', StepStatus::IN_PROGRESS);

        return back()->with('success', 'HR Policy OS data saved successfully.');
    }

    /**
     * Submit HR Policy OS for CEO review.
     */
    public function submit(Request $request, HrProject $hrProject)
    {
        if (!$request->user()->hasRole('hr_manager')) {
            abort(403);
        }

        // Validate that required sections are completed
        $hrPolicyOs = \App\Models\HrPolicyOs::where('hr_project_id', $hrProject->id)->first();
        
        if (!$hrPolicyOs) {
            return back()->withErrors(['error' => 'Please complete the HR Policy OS before submitting.']);
        }

        // Submit the step
        $this->stepTransitionService->submitStep($hrProject, 'hr_policy_os');

        return redirect()->route('hr-manager.dashboard')
            ->with('success', 'HR Policy OS submitted for CEO review.');
    }

    /**
     * CEO review of HR Policy OS.
     */
    public function ceoReview(Request $request, HrProject $hrProject)
    {
        if (!$request->user()->hasRole('ceo')) {
            abort(403);
        }

        // Check if CEO is associated with the company
        if (!$hrProject->company->users->contains($request->user())) {
            abort(403);
        }

        // Load all necessary data
        $hrProject->load([
            'diagnosis',
            'company',
            'ceoPhilosophy',
            'organizationDesign',
            'performanceSystem',
            'compensationSystem',
        ]);

        $hrPolicyOs = \App\Models\HrPolicyOs::where('hr_project_id', $hrProject->id)->first();

        if (!$hrPolicyOs) {
            return redirect()->route('ceo.dashboard')
                ->withErrors(['error' => 'HR Policy OS has not been submitted yet.']);
        }

        $stepStatuses = $hrProject->step_statuses ?? [];

        return Inertia::render('HrPolicyOs/CeoReview', [
            'project' => $hrProject,
            'hrPolicyOs' => $hrPolicyOs,
            'stepStatuses' => $stepStatuses,
        ]);
    }

    /**
     * CEO approve HR Policy OS (final step).
     */
    public function approve(Request $request, HrProject $hrProject)
    {
        if (!$request->user()->hasRole('ceo')) {
            abort(403);
        }

        // Check if CEO is associated with the company
        if (!$hrProject->company->users->contains($request->user())) {
            abort(403);
        }

        $currentStatus = $hrProject->getStepStatus('hr_policy_os');

        if (!$currentStatus || $currentStatus !== StepStatus::SUBMITTED) {
            return back()->withErrors(['error' => 'HR Policy OS must be submitted before approval.']);
        }

        // Approve and lock the final step
        $this->stepTransitionService->approveAndLockStep($hrProject, 'hr_policy_os');

        // Mark entire system as locked
        $hrProject->update(['status' => \App\Enums\ProjectStatus::LOCKED]);

        return redirect()->route('ceo.dashboard')
            ->with('success', 'HR Policy OS approved and system locked. The Pathfinder journey is complete!');
    }

    /**
     * Auto-generate policy manual from Steps 1-4.
     */
    protected function generatePolicyManual(HrProject $hrProject, $jobDefinitions): array
    {
        $diagnosis = $hrProject->diagnosis;
        $ceoPhilosophy = $hrProject->ceoPhilosophy;
        $performanceSystem = $hrProject->performanceSystem;
        $compensationSystem = $hrProject->compensationSystem;
        $company = $hrProject->company;

        // Generate Company HR Philosophy
        $companyPhilosophy = "Company: {$company->name}\n\n";
        if ($ceoPhilosophy) {
            $companyPhilosophy .= "Management Philosophy: ";
            if ($ceoPhilosophy->growth_stage) {
                $companyPhilosophy .= "Growth Stage - {$ceoPhilosophy->growth_stage}\n";
            }
            if ($ceoPhilosophy->main_trait) {
                $companyPhilosophy .= "Primary Trait: {$ceoPhilosophy->main_trait}\n";
            }
            if ($ceoPhilosophy->concerns) {
                $companyPhilosophy .= "Key Concerns: {$ceoPhilosophy->concerns}\n";
            }
        }
        if ($diagnosis) {
            $companyPhilosophy .= "\nIndustry: " . ($diagnosis->industry_category ?? 'Not specified');
            if ($diagnosis->industry_subcategory) {
                $companyPhilosophy .= " - {$diagnosis->industry_subcategory}";
            }
        }

        // Generate Job Architecture Policy
        $jobArchitecture = "Job Architecture Policy\n\n";
        $jobArchitecture .= "Total Job Roles: " . $jobDefinitions->count() . "\n\n";
        $jobArchitecture .= "Job Families:\n";
        $jobGroups = $jobDefinitions->groupBy(function ($job) {
            return $job->jobKeyword->category ?? 'Other';
        });
        foreach ($jobGroups as $group => $jobs) {
            $jobArchitecture .= "- {$group}: " . $jobs->count() . " roles\n";
        }

        // Generate Performance Management Policy
        $performancePolicy = "Performance Management Policy\n\n";
        if ($performanceSystem) {
            $performancePolicy .= "Performance Method: " . ($performanceSystem->performance_method ?? 'Not specified') . "\n";
            $performancePolicy .= "Evaluation Unit: " . ($performanceSystem->evaluation_unit ?? 'Not specified') . "\n";
            if ($performanceSystem->evaluation_logic) {
                $performancePolicy .= "Evaluation Logic: {$performanceSystem->evaluation_logic}\n";
            }
        } else {
            $performancePolicy .= "Performance system not yet configured.\n";
        }

        // Generate Compensation & Benefits Policy
        $compensationPolicy = "Compensation & Benefits Policy\n\n";
        if ($compensationSystem) {
            $compensationPolicy .= "Compensation Structure: " . ($compensationSystem->compensation_structure ?? 'Not specified') . "\n";
            $compensationPolicy .= "Differentiation Logic: " . ($compensationSystem->differentiation_logic ?? 'Not specified') . "\n";
            if ($compensationSystem->incentive_types && is_array($compensationSystem->incentive_types)) {
                $compensationPolicy .= "Incentive Types: " . implode(', ', $compensationSystem->incentive_types) . "\n";
            }
        } else {
            $compensationPolicy .= "Compensation system not yet configured.\n";
        }

        // Generate Governance
        $governance = "Governance & Decision Authority\n\n";
        $governance .= "Step Review Process:\n";
        $governance .= "- HR Manager: Inputs and submits each step\n";
        $governance .= "- CEO: Reviews and approves each step\n";
        $governance .= "- Admin/Consultant: Provides recommendations\n\n";
        $governance .= "Final Approval: CEO must approve Step 5 to lock the system.\n";

        // Generate Review Policy
        $reviewPolicy = "Review & Change Management Policy\n\n";
        $reviewPolicy .= "Once a step is locked, changes require:\n";
        $reviewPolicy .= "- Admin override permission\n";
        $reviewPolicy .= "- CEO re-approval\n";
        $reviewPolicy .= "- Automatic version increment\n";

        // Generate System Handbook
        $systemHandbook = [
            'overview' => "HR System Overview\n\nThis handbook explains how the HR systems work internally. All systems are designed based on company diagnosis, CEO philosophy, and organizational structure.",
            'performance_measurement' => $performancePolicy,
            'reward_structure' => $compensationPolicy,
            'job_roles' => "Job roles are defined through the Job Analysis step. Each role has:\n- Job Description\n- Job Specification\n- Competency Levels\n- Critical Success Factors",
            'governance' => $governance,
            'communication' => "Employee Communication Guidelines\n\n- All HR policies should be communicated clearly to employees\n- Training sessions should be conducted for new systems\n- Regular updates should be provided on policy changes",
        ];

        // Generate Implementation Roadmap
        $implementationRoadmap = [
            'rollout_sequence' => 'Performance System → Compensation System → Policy Rollout',
            'pilot_group' => 'Management Team',
            'communication_plan' => "Phase 1: Announcement via company-wide email\nPhase 2: Department meetings\nPhase 3: Training sessions\nPhase 4: Q&A sessions",
            'training_responsibility' => 'HR Department with support from Managers',
            'timeline' => '6 months',
            'risks' => "Key Risks:\n- Resistance to change\n- Lack of understanding\n- Implementation delays\n\nMitigation:\n- Clear communication\n- Comprehensive training\n- Phased rollout approach",
        ];

        // Generate Analytics Blueprint
        $analyticsBlueprint = [
            'performance_distribution' => "Performance Distribution Health\n\nFormula: Count of employees by performance rating / Total employees\nTarget: Normal distribution with majority in 'Meets Expectations'",
            'pay_equity' => "Pay Equity Indicators\n\nFormula: Compare compensation within same job grade and performance level\nTarget: <5% variance for similar roles and performance",
            'role_clarity' => "Role Clarity Index\n\nFormula: Survey score on role understanding (1-5 scale)\nTarget: Average score >4.0",
            'turnover_risk' => "Turnover Risk by Job Family\n\nFormula: (Employees with low performance + low engagement) / Total in job family\nTarget: <10% high-risk employees per job family",
            'performance_reward_correlation' => "Performance-to-Reward Correlation\n\nFormula: Correlation coefficient between performance ratings and compensation increases\nTarget: >0.7 correlation",
        ];

        return [
            'policy_manual' => [
                'company_philosophy' => $companyPhilosophy,
                'job_architecture_policy' => $jobArchitecture,
                'performance_policy' => $performancePolicy,
                'compensation_policy' => $compensationPolicy,
                'governance' => $governance,
                'review_policy' => $reviewPolicy,
            ],
            'system_handbook' => $systemHandbook,
            'implementation_roadmap' => $implementationRoadmap,
            'analytics_blueprint' => $analyticsBlueprint,
        ];
    }
}
